- name: To practice ansible today.
  hosts: devops
  become: yes
  vars_prompt:
  - name: User
    prompt: "Hi please enter your name"
  tasks:
  - name: To work with variables
    ansible.builtin.debug:
     msg: "Hi {{User}}, you will be back on track very soon"