- name: TO install nginx
  hosts: web
  tasks:
  - name: To install nginx
    ansible.builtin.package:
     name: nginx
     state: present

- name: TO install nginx
  hosts: web
  tasks:
  - name: To install nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes