- name: To practice Ansible
  hosts: devopss
  become: yes
  gather_facts: yes
  vars_files:  
  - vars.yaml
  tasks:
  - name: To display a message
    ansible.builtin.debug:
     msg: "{{person}} you need to improve focus on things which are really matter to you"