- name: TO install nginx
  hosts: web
  become: yes 
  gather_facts: no
  vars:
   number: 11
  tasks:
  - name: To install nginx
    ansible.builtin.debug:
     msg: "{{item}}"
    loop:
    - Hi
    - Hello
    - haha