- name: To practice Ansible
  hosts: devopss
  become: yes
  gather_facts: yes
  tasks: 
  - name: To check for user
    ansible.builtin.debug: 
     msg: "{{item}}"
    loop:
    - one
    - two
    - three
    - four
    - five