- name: To install packages
  become: yes
  hosts: web
  tasks:
  - name: To install nginx
    ansible.builtin.package:
    name: nginx
    state: present
  - name: To start nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
