- name: To practice Ansible
  hosts: devopss
  become: yes
  gather_facts: yes
  vars:
   duration: 120
  tasks:
  - name: To display a message
    ansible.builtin.debug:
     msg: "{{duration}} hours for your ansible session"